// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gVo1bJVU5dTgrPwqHUv3VhqIJg7jNAI',
    appId: '1:503865299413:web:31058971bed25cdb4bed5c',
    messagingSenderId: '503865299413',
    projectId: 'sabzi-wala-app',
    authDomain: 'sabzi-wala-app.firebaseapp.com',
    databaseURL: 'https://sabzi-wala-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sabzi-wala-app.firebasestorage.app',
    measurementId: 'G-L5NLJ3DXC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqTf3BpdLXO33RTwOlph2ZPYzJ1_G_14',
    appId: '1:503865299413:android:35e20dd70223d1524bed5c',
    messagingSenderId: '503865299413',
    projectId: 'sabzi-wala-app',
    databaseURL: 'https://sabzi-wala-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sabzi-wala-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLcTgRf5UR0CSoiqqI15en7iRRjO7OOA',
    appId: '1:503865299413:ios:5959027b3b5e3e044bed5c',
    messagingSenderId: '503865299413',
    projectId: 'sabzi-wala-app',
    databaseURL: 'https://sabzi-wala-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sabzi-wala-app.firebasestorage.app',
    iosBundleId: 'com.example.sabziWalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaLcTgRf5UR0CSoiqqI15en7iRRjO7OOA',
    appId: '1:503865299413:ios:5959027b3b5e3e044bed5c',
    messagingSenderId: '503865299413',
    projectId: 'sabzi-wala-app',
    databaseURL: 'https://sabzi-wala-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sabzi-wala-app.firebasestorage.app',
    iosBundleId: 'com.example.sabziWalaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8gVo1bJVU5dTgrPwqHUv3VhqIJg7jNAI',
    appId: '1:503865299413:web:3a8f607cfc9f0b784bed5c',
    messagingSenderId: '503865299413',
    projectId: 'sabzi-wala-app',
    authDomain: 'sabzi-wala-app.firebaseapp.com',
    databaseURL: 'https://sabzi-wala-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sabzi-wala-app.firebasestorage.app',
    measurementId: 'G-7L931F3H0M',
  );

}